name: MultiSpawns
description: MultiSpawns
main: com.connorlinfoot.multispawns.MultiSpawns
version: 1.0-SNAPSHOT
authors: [Connor Linfoot]
commands:
  addspawn:
    description: Add spawn command
  delspawn:
    description: Delete spawn command
  multispawns:
    aliases: [ms]
    description: MultiSpawns command
permissions:
  multispawn.admin:
    default: op