name: MultiSpawns
description: A plugin that allows you to have multiple spawns on your server.
main: com.connorlinfoot.multispawns.MultiSpawns
version: 1.1-SNAPSHOT
authors: [Connor Linfoot]
commands:
  addspawn:
    description: Add spawn command
  delspawn:
    description: Delete spawn command
  multispawns:
    aliases: [ms]
    description: MultiSpawns command
  spawn:
    description: Spawn command
permissions:
  multispawn.admin:
    default: op
  multispawn.spawn:
    default: true